import { Users, Heart, MessageSquare, Radio, AlertCircle, Globe, Brain } from 'lucide-react'

export default function AudiencePanel({ audience }) {
  if (!audience) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-8">
        <div className="w-16 h-16 rounded-2xl bg-slate-800 border border-slate-700 flex items-center justify-center mb-4">
          <Users className="w-8 h-8 text-slate-600" />
        </div>
        <h3 className="text-slate-400 font-medium mb-1">Audience Not Yet Defined</h3>
        <p className="text-sm text-slate-600">Audience segments will appear after strategy generation</p>
      </div>
    )
  }

  const primary = audience.primary_segment || {}
  const secondary = audience.secondary_segment || {}
  const targeting = audience.targeting_parameters || {}
  const sizing = audience.audience_sizing || {}
  const persona = audience.persona_narrative || {}
  const llmUsed = audience._llm_used || 'AI'

  return (
    <div className="p-5 space-y-5 overflow-y-auto h-full">
      {/* LLM Badge */}
      <div className="flex items-center gap-2">
        <span className="text-xs bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 px-2.5 py-1 rounded-full flex items-center gap-1">
          <Brain className="w-3 h-3" />
          Generated by: {llmUsed === 'ollama' ? `Ollama (${audience._llm_model || 'llama3.2'})` : 'Claude'}
        </span>
        {sizing.total_addressable_market && (
          <span className="text-xs bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-2.5 py-1 rounded-full">
            TAM: {sizing.total_addressable_market}
          </span>
        )}
      </div>

      {/* Primary Segment */}
      <div className="glass-card p-5 border-l-4 border-l-cyan-500">
        <div className="flex items-center gap-2 mb-4">
          <Users className="w-4 h-4 text-cyan-400" />
          <h3 className="font-semibold text-slate-200">Primary Segment</h3>
          <span className="ml-auto text-xs bg-cyan-500/10 text-cyan-400 px-2 py-0.5 rounded-full">Primary</span>
        </div>

        <div className="mb-3">
          <h4 className="text-lg font-bold text-white">{primary.name}</h4>
          <p className="text-sm text-slate-400 mt-1">{primary.description}</p>
        </div>

        <div className="grid grid-cols-2 gap-3 mb-4">
          {[
            { label: 'Age Range', value: primary.age_range },
            { label: 'Gender Split', value: primary.gender_split },
            { label: 'Income Level', value: primary.income_level },
            { label: 'Education', value: primary.education },
            { label: 'Location', value: primary.location },
            { label: 'Market Size', value: primary.estimated_market_size },
          ].filter(f => f.value).map(({ label, value }) => (
            <div key={label} className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/30">
              <p className="text-xs text-slate-500 mb-0.5">{label}</p>
              <p className="text-sm font-medium text-slate-200">{value}</p>
            </div>
          ))}
        </div>

        {primary.psychographics && (
          <div className="mb-4">
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2">Psychographics</p>
            <p className="text-sm text-slate-400 mb-2">{primary.psychographics.lifestyle}</p>
            <div className="flex flex-wrap gap-1.5">
              {(primary.psychographics.values || []).map((v, i) => (
                <span key={i} className="text-xs bg-slate-800 border border-slate-700 text-slate-300 px-2.5 py-1 rounded-full">{v}</span>
              ))}
              {(primary.psychographics.personality_traits || []).map((t, i) => (
                <span key={i} className="text-xs bg-purple-500/10 border border-purple-500/20 text-purple-300 px-2.5 py-1 rounded-full">{t}</span>
              ))}
            </div>
          </div>
        )}

        <TwoColumnList
          leftTitle="Pain Points"
          leftItems={primary.pain_points}
          leftColor="text-danger"
          leftIcon="⚡"
          rightTitle="Motivations"
          rightItems={primary.motivations}
          rightColor="text-success"
          rightIcon="✨"
        />
      </div>

      {/* Persona Narrative */}
      {persona.primary_day_in_life && (
        <div className="glass-card p-4">
          <div className="flex items-center gap-2 mb-3">
            <MessageSquare className="w-4 h-4 text-purple-400" />
            <h3 className="font-semibold text-slate-200 text-sm">Persona Narrative</h3>
          </div>
          <blockquote className="text-sm text-slate-400 italic border-l-2 border-purple-500/50 pl-3 mb-3">
            "{persona.primary_day_in_life}"
          </blockquote>
          {persona.key_insight && (
            <div className="bg-purple-500/5 border border-purple-500/20 rounded-xl p-3">
              <p className="text-xs font-medium text-purple-400 mb-1">Key Insight</p>
              <p className="text-sm text-slate-300">{persona.key_insight}</p>
            </div>
          )}
          {persona.emotional_driver && (
            <div className="mt-2 flex items-center gap-2">
              <Heart className="w-3.5 h-3.5 text-danger" />
              <p className="text-xs text-slate-400"><span className="text-danger font-medium">Emotional Driver:</span> {persona.emotional_driver}</p>
            </div>
          )}
        </div>
      )}

      {/* Secondary Segment */}
      {secondary.name && (
        <div className="glass-card p-4 border-l-4 border-l-purple-500">
          <div className="flex items-center gap-2 mb-3">
            <Users className="w-4 h-4 text-purple-400" />
            <h3 className="font-semibold text-slate-200 text-sm">Secondary Segment</h3>
            <span className="ml-auto text-xs bg-purple-500/10 text-purple-400 px-2 py-0.5 rounded-full">Secondary</span>
          </div>
          <h4 className="font-bold text-white mb-1">{secondary.name}</h4>
          <p className="text-sm text-slate-400 mb-3">{secondary.description}</p>
          <div className="grid grid-cols-2 gap-2 text-xs">
            {secondary.age_range && <InfoChip label="Age" value={secondary.age_range} />}
            {secondary.income_level && <InfoChip label="Income" value={secondary.income_level} />}
            {secondary.location && <InfoChip label="Location" value={secondary.location} />}
          </div>
        </div>
      )}

      {/* Targeting Parameters */}
      {Object.keys(targeting).length > 0 && (
        <div className="glass-card p-4">
          <div className="flex items-center gap-2 mb-3">
            <Radio className="w-4 h-4 text-orange-400" />
            <h3 className="font-semibold text-slate-200 text-sm">Ad Targeting Parameters</h3>
          </div>
          {targeting.demographic_targeting?.length > 0 && (
            <TagGroup label="Demographics" items={targeting.demographic_targeting} color="orange" />
          )}
          {targeting.interest_targeting?.length > 0 && (
            <TagGroup label="Interests" items={targeting.interest_targeting} color="cyan" />
          )}
          {targeting.behavioral_targeting?.length > 0 && (
            <TagGroup label="Behavioral" items={targeting.behavioral_targeting} color="emerald" />
          )}
          {targeting.lookalike_seed_audience && (
            <div className="mt-2">
              <p className="text-xs text-slate-500 mb-1">Lookalike Seed Audience</p>
              <p className="text-sm text-slate-300">{targeting.lookalike_seed_audience}</p>
            </div>
          )}
        </div>
      )}

      {/* Negative Audience */}
      {audience.negative_audience && (
        <div className="glass-card p-4 border border-danger/20">
          <div className="flex items-center gap-2 mb-2">
            <AlertCircle className="w-4 h-4 text-danger" />
            <h3 className="font-semibold text-slate-200 text-sm">Negative Audience (Exclude)</h3>
          </div>
          <p className="text-sm text-slate-400 mb-2">{audience.negative_audience.description}</p>
          <ul className="space-y-1">
            {(audience.negative_audience.exclusions || []).map((ex, i) => (
              <li key={i} className="text-xs text-danger flex gap-1.5"><span>✗</span>{ex}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

function TwoColumnList({ leftTitle, leftItems, leftColor, leftIcon, rightTitle, rightItems, rightColor, rightIcon }) {
  const items = Math.max((leftItems || []).length, (rightItems || []).length)
  if (items === 0) return null
  return (
    <div className="grid grid-cols-2 gap-3 mt-3">
      <div>
        <p className={`text-xs font-medium mb-2 ${leftColor}`}>{leftIcon} {leftTitle}</p>
        <ul className="space-y-1.5">
          {(leftItems || []).slice(0, 4).map((item, i) => (
            <li key={i} className="text-xs text-slate-400 flex gap-1.5"><span>•</span>{item}</li>
          ))}
        </ul>
      </div>
      <div>
        <p className={`text-xs font-medium mb-2 ${rightColor}`}>{rightIcon} {rightTitle}</p>
        <ul className="space-y-1.5">
          {(rightItems || []).slice(0, 4).map((item, i) => (
            <li key={i} className="text-xs text-slate-400 flex gap-1.5"><span>•</span>{item}</li>
          ))}
        </ul>
      </div>
    </div>
  )
}

function TagGroup({ label, items, color }) {
  const colorMap = {
    orange: 'bg-orange-500/10 border-orange-500/20 text-orange-300',
    cyan: 'bg-cyan-500/10 border-cyan-500/20 text-cyan-300',
    emerald: 'bg-emerald-500/10 border-emerald-500/20 text-emerald-300',
  }
  return (
    <div className="mb-2">
      <p className="text-xs text-slate-500 mb-1.5">{label}</p>
      <div className="flex flex-wrap gap-1">
        {(items || []).slice(0, 8).map((item, i) => (
          <span key={i} className={`text-xs border px-2 py-0.5 rounded-full ${colorMap[color]}`}>{item}</span>
        ))}
      </div>
    </div>
  )
}

function InfoChip({ label, value }) {
  return (
    <div className="bg-slate-800 rounded-lg p-2 border border-slate-700/50">
      <p className="text-slate-500 text-xs">{label}</p>
      <p className="text-slate-300">{value}</p>
    </div>
  )
}
